### ISSUE TITLE
Issue with Vector observation

### ISSUE THREAD

**Issue by LucaVendruscolo** [Eclectic-Sheep/sheeprl#246]
Hello, I have been trying to implement this marble maze game using dreamerV3. I have tried to follow #162 to try to implement dreamer without the image observation but I couldn't understand what to do. 

Link to download the SheepRL folder I added the custom environment and the config file too
https://drive.google.com/file/d/114g42Mub6ksW-y_wgO6_XxTsxftROXRr/view?usp=sharing

I have made a game and put it into a custom gym environment but I get this error message when I try to run python sheeprl.py exp=dreamer_v3 env=BallGame:

<details>
<summary>Error Logs</summary>
```powershell

(RL17) C:\Users\lucav\Downloads\SheepRLFromScratch\sheeprl>python sheeprl.py exp=dreamer_v3 env=BallGame  
CONFIG
├── algo
│   └── name: dreamer_v3
│       total_steps: 5000000
│       per_rank_batch_size: 16
│       run_test: true
│       cnn_keys:
│         encoder:
│         - rgb
│         decoder:
│         - rgb
│       mlp_keys:
│         encoder: []
│         decoder: []
│       world_model:
│         optimizer:
│           _target_: torch.optim.Adam
│           lr: 0.0001
│           eps: 1.0e-08
│           weight_decay: 0
│           betas:
│           - 0.9
│           - 0.999
│         discrete_size: 32
│         stochastic_size: 32
│         kl_dynamic: 0.5
│         kl_representation: 0.1
│         kl_free_nats: 1.0
│         kl_regularizer: 1.0
│         continue_scale_factor: 1.0
│         clip_gradients: 1000.0
│         encoder:
│           cnn_channels_multiplier: 32
│           cnn_act: torch.nn.SiLU
│           dense_act: torch.nn.SiLU
│           mlp_layers: 2
│           layer_norm: true
│           dense_units: 512
│         recurrent_model:
│           recurrent_state_size: 512
│           layer_norm: true
│           dense_units: 512
│         transition_model:
│           hidden_size: 512
│           dense_act: torch.nn.SiLU
│           layer_norm: true
│         representation_model:
│           hidden_size: 512
│           dense_act: torch.nn.SiLU
│           layer_norm: true
│         observation_model:
│           cnn_channels_multiplier: 32
│           cnn_act: torch.nn.SiLU
│           dense_act: torch.nn.SiLU
│           mlp_layers: 2
│           layer_norm: true
│           dense_units: 512
│         reward_model:
│           dense_act: torch.nn.SiLU
│           mlp_layers: 2
│           layer_norm: true
│           dense_units: 512
│           bins: 255
│         discount_model:
│           learnable: true
│           dense_act: torch.nn.SiLU
│           mlp_layers: 2
│           layer_norm: true
│           dense_units: 512
│       actor:
│         optimizer:
│           _target_: torch.optim.Adam
│           lr: 8.0e-05
│           eps: 1.0e-05
│           weight_decay: 0
│           betas:
│           - 0.9
│           - 0.999
│         cls: sheeprl.algos.dreamer_v3.agent.Actor
│         ent_coef: 0.0003
│         min_std: 0.1
│         init_std: 0.0
│         objective_mix: 1.0
│         dense_act: torch.nn.SiLU
│         mlp_layers: 2
│         layer_norm: true
│         dense_units: 512
│         clip_gradients: 100.0
│         expl_amount: 0.0
│         expl_min: 0.0
│         expl_decay: false
│         max_step_expl_decay: 0
│         moments:
│           decay: 0.99
│           max: 1.0
│           percentile:
│             low: 0.05
│             high: 0.95
│       critic:
│         optimizer:
│           _target_: torch.optim.Adam
│           lr: 8.0e-05
│           eps: 1.0e-05
│           weight_decay: 0
│           betas:
│           - 0.9
│           - 0.999
│         dense_act: torch.nn.SiLU
│         mlp_layers: 2
│         layer_norm: true
│         dense_units: 512
│         target_network_update_freq: 1
│         tau: 0.02
│         bins: 255
│         clip_gradients: 100.0
│       gamma: 0.996996996996997
│       lmbda: 0.95
│       horizon: 15
│       train_every: 16
│       learning_starts: 65536
│       per_rank_pretrain_steps: 1
│       per_rank_gradient_steps: 1
│       per_rank_sequence_length: 64
│       layer_norm: true
│       dense_units: 512
│       mlp_layers: 2
│       dense_act: torch.nn.SiLU
│       cnn_act: torch.nn.SiLU
│       unimix: 0.01
│       hafner_initialization: true
│       decoupled_rssm: false
│       player:
│         discrete_size: 32
│       
├── buffer
│   └── size: 1000000
│       memmap: true
│       validate_args: false
│       from_numpy: false
│       checkpoint: false
│       
├── checkpoint
│   └── every: 100000
│       resume_from: null
│       save_last: true
│       keep_last: 5
│       
├── env
│   └── id: BallGame
│       num_envs: 4
│       frame_stack: 1
│       sync_env: false
│       screen_size: 64
│       action_repeat: 1
│       grayscale: false
│       clip_rewards: false
│       capture_video: false
│       frame_stack_dilation: 1
│       max_episode_steps: null
│       reward_as_observation: false
│       wrapper:
│         _target_: sheeprl.envs.BallGame.BallEnv
│         render_mode: rgb_array
│       algo:
│         mlp_keys:
│           encoder:
│           - position
│           decoder:
│           - position
│       
├── fabric
│   └── _target_: lightning.fabric.Fabric
│       devices: 1
│       num_nodes: 1
│       strategy: auto
│       accelerator: gpu
│       precision: 32-true
│       callbacks:
│       - _target_: sheeprl.utils.callback.CheckpointCallback
│         keep_last: 5
│       
└── metric
    └── log_every: 5000
        disable_timer: false
        log_level: 1
        sync_on_compute: false
        aggregator:
          _target_: sheeprl.utils.metric.MetricAggregator
          raise_on_missing: false
          metrics:
            Rewards/rew_avg:
              _target_: torchmetrics.MeanMetric
              sync_on_compute: false
            Game/ep_len_avg:
              _target_: torchmetrics.MeanMetric
              sync_on_compute: false
            Loss/world_model_loss:
              _target_: torchmetrics.MeanMetric
              sync_on_compute: false
            Loss/value_loss:
              _target_: torchmetrics.MeanMetric
              sync_on_compute: false
            Loss/policy_loss:
              _target_: torchmetrics.MeanMetric
              sync_on_compute: false
            Loss/observation_loss:
              _target_: torchmetrics.MeanMetric
              sync_on_compute: false
            Loss/reward_loss:
              _target_: torchmetrics.MeanMetric
              sync_on_compute: false
            Loss/state_loss:
              _target_: torchmetrics.MeanMetric
              sync_on_compute: false
            Loss/continue_loss:
              _target_: torchmetrics.MeanMetric
              sync_on_compute: false
            State/kl:
              _target_: torchmetrics.MeanMetric
              sync_on_compute: false
            State/post_entropy:
              _target_: torchmetrics.MeanMetric
              sync_on_compute: false
            State/prior_entropy:
              _target_: torchmetrics.MeanMetric
              sync_on_compute: false
            Params/exploration_amount:
              _target_: torchmetrics.MeanMetric
              sync_on_compute: false
            Grads/world_model:
              _target_: torchmetrics.MeanMetric
              sync_on_compute: false
            Grads/actor:
              _target_: torchmetrics.MeanMetric
              sync_on_compute: false
            Grads/critic:
              _target_: torchmetrics.MeanMetric
              sync_on_compute: false
        logger:
          _target_: lightning.fabric.loggers.TensorBoardLogger
          name: 2024-03-28_23-07-38_dreamer_v3_BallGame_42
          root_dir: logs/runs/dreamer_v3/BallGame
          version: null
          default_hp_metric: true
          prefix: ''
          sub_dir: null
        
Seed set to 42
C:\Users\lucav\Downloads\SheepRLFromScratch\sheeprl\sheeprl\utils\logger.py:22: UserWarning: The specified root directory for the TensorBoardLogger is different from the experiment one, so the logger one will be ignored and replaced with the experiment root directory
  warnings.warn(
Log dir: logs\runs\dreamer_v3/BallGame\2024-03-28_23-07-38_dreamer_v3_BallGame_42\version_0
Error executing job with overrides: ['exp=dreamer_v3', 'env=BallGame']
Traceback (most recent call last):
  File "C:\Users\lucav\Downloads\SheepRLFromScratch\sheeprl\sheeprl\cli.py", line 347, in run
    run_algorithm(cfg)
  File "C:\Users\lucav\Downloads\SheepRLFromScratch\sheeprl\sheeprl\cli.py", line 186, in run_algorithm
    fabric.launch(reproducible(command), cfg, **kwargs)
  File "C:\Users\lucav\Downloads\SheepRLFromScratch\RL17\lib\site-packages\lightning\fabric\fabric.py", line 839, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "C:\Users\lucav\Downloads\SheepRLFromScratch\RL17\lib\site-packages\lightning\fabric\fabric.py", line 925, in _wrap_and_launch
    return to_run(*args, **kwargs)
  File "C:\Users\lucav\Downloads\SheepRLFromScratch\RL17\lib\site-packages\lightning\fabric\fabric.py", line 930, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "C:\Users\lucav\Downloads\SheepRLFromScratch\sheeprl\sheeprl\cli.py", line 182, in wrapper
    return func(fabric, cfg, *args, **kwargs)
  File "C:\Users\lucav\Downloads\SheepRLFromScratch\sheeprl\sheeprl\algos\dreamer_v3\dreamer_v3.py", line 407, in main
    envs = vectorized_env(
  File "C:\Users\lucav\Downloads\SheepRLFromScratch\RL17\lib\site-packages\gymnasium\vector\async_vector_env.py", line 105, in __init__
    dummy_env = env_fns[0]()
  File "C:\Users\lucav\Downloads\SheepRLFromScratch\sheeprl\sheeprl\envs\wrappers.py", line 83, in __init__
    super().__init__(self._env_fn())
  File "C:\Users\lucav\Downloads\SheepRLFromScratch\sheeprl\sheeprl\utils\env.py", line 111, in thunk
    env = gym.wrappers.PixelObservationWrapper(
  File "C:\Users\lucav\Downloads\SheepRLFromScratch\RL17\lib\site-packages\gymnasium\wrappers\pixel_observation.py", line 106, in __init__
    raise AttributeError(
AttributeError: env.render_mode must be specified to use PixelObservationWrapper:`gymnasium.make(env_name, render_mode='rgb_array')`.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
``` 
</details>

**Comment by michele-milesi** [comment]
Hi @LucaVendruscolo,
if you want to use only the flat vector observations (and not the image observations), you must specify the `algo.mlp_keys` and the `algo.cnn_keys` in the configs.
If you take a look at the configs that you reported, you can observe that the `algo.cnn_keys.encoder` and  `algo.cnn_keys.decoder` are set to `rgb`, whereas the mlp_keys (both encoder and decoder) are empty:

> │ cnn_keys:
> │ encoder:
> │ - rgb
> │ decoder:
> │ - rgb
> │ mlp_keys:
> │ encoder: []
> │ decoder: []

By default, when the environment provides only vector observations and if the user specifies the cnn_keys in the configs, the image observations are retrieved from the render function of the environment.

So you have to run the following command:
`exp=dreamer_v3 env=BallGame algo.mlp_keys.encoder=[position] algo.mlp_keys.encoder=[position] algo.cnn_keys.encoder=[] algo.cnn_keys.decoder=[]`


There is another problem in your environment: in the step and reset function you return a Python dictionary as observation, but the type of the observation space of the environment is `gymnasium.spaces.Box`.
You should replace
```python
self.observation_space = gym.spaces.Box(low=np.array([0, 0]), high=np.array([self.screen_width, self.screen_height]), dtype=np.float32)
```
with
```python
self.observation_space = gym.spaces.Dict({
    "position": gym.spaces.Box(low=np.array([0, 0]), high=np.array([self.screen_width, self.screen_height]), dtype=np.float32
})
```

Finally, I suggest to add `self.render_mode=render_mode` in the __init__ method.

Let me know if it works.

**Comment by LucaVendruscolo** [comment]
It works thank you!

**Comment by michele-milesi** [comment]
I am closing this issue, feel free to reopen it if you have further questions or open a new one for a new topic.

**Comment by LucaVendruscolo** [comment]
Hello, I was wondering if you had any advice on how I could improve my program as it currently doesn't seem to be learning very well. The goal of the game is to explore the largest possible area of the 'maze,' aiming to create as much grey area as possible. Initially, the program's observation space included only its position, and it received rewards based on the amount of new grey area it uncovered with each step. However, this led to the program getting stuck at a local optimum of just b lining it for the closest wall every game.

To try to fix this, I've made the observation space include the position, velocity, and acceleration of the ball (The agent controls its acceleration, which can be adjusted by a max of ±0.2 at each step with an upper/lower bound of +-1) The reward now gives +1 for exploring new area and -1 for not exploring. Despite these changes, after running 35,000 games (10 hours of simulation) the program reaches a local optimum of again of just running into the nearest wall.

I have tried:
Observation space of:
- just velocty
- velocity and speed
- velocity speed and acceleration

A reward of:
- New grey area created each step (which I think just made it go as fast as possible)
- flat +1 for having created new area or -1 for not
- giving the total area at the end of the game as reward and none during the game
- giving a big negative reward for dying while having the reward be +1 or -1 for having/not having created new area

But all of them still just seem to end up b lining it for the wall.

Ignore the title of the graph. The graph shows the total reward the agent got every game (this is the +1 -1 reward one but they all dont have a clear pattern of improvement)
<img width="955" alt="Screenshot 2024-03-31 at 12 04 57 am" src="https://github.com/Eclectic-Sheep/sheeprl/assets/71438132/8f2af07d-cae9-43c2-9e5e-f797e320697b">


Link to the SheepRL folder if you would like to take a look at the code:
https://drive.google.com/file/d/1wCbGbIOWs4_cPqP6TuWoB6NK472Xp34_/view?usp=sharing

Any advice would be much appreciated!

**Comment by belerico** [comment]
Hi @LucaVendruscolo, the first thing that it comes to my mind is to add a higher entropy-bonus so to have a more explorative policy: which agent are you using to learn in this environment?

**Comment by LucaVendruscolo** [comment]
thanks for the help. I am using DreamerV3. How do I increase the entropy-bonus?

**Comment by LucaVendruscolo** [comment]
Hi Belerico. Thanks for the advice. I think my environment has rewards that are just not clear enough for the model. I will try to increase the entropy-bonus and see if that makes a difference.
